# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8d35320e4792e1a756b80e340164dd660156c254ac0c6a4e63ce55b4c49fb6d82f8fa9f18f007e09bc676fce0bb1ba98f1d8453daea8468b0c900dc2c0beb0b

test:
  secret_key_base: 8ed799df57245a8bafff7588f0bde2369aadf089cbce47d39b903295e9a2bdd74780f0dc4e6fd26590829940c330dff70a2c15ce1eece52647231a54db69daf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
